name: SEBAR Tv - Universal Video to HLS

on:
  workflow_dispatch:
    inputs:
      video_url:
        description: 'Direct Video URL'
        required: true
      folder_name:
        description: 'Folder Name (English only)'
        required: true

jobs:
  convert_and_upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install FFmpeg
        run: sudo apt-get update && sudo apt-get install -y ffmpeg

      - name: Download Video
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: wget --header="Authorization: Bearer $HF_TOKEN" -O input_video "${{ github.event.inputs.video_url }}"

      - name: Create HLS Chunks
        run: |
          mkdir -p output/${{ github.event.inputs.folder_name }}
          ffmpeg -i input_video -map 0:V:0 -map 0:a? -vf "scale=trunc(iw/2)*2:trunc(ih/2)*2" -c:v libx264 -preset ultrafast -pix_fmt yuv420p -crf 26 -g 60 -sc_threshold 0 -c:a aac -b:a 128k -hls_time 10 -hls_list_size 0 -hls_segment_filename "output/${{ github.event.inputs.folder_name }}/index%d.ts" output/${{ github.event.inputs.folder_name }}/index.m3u8

      - name: Rename Extensions to .safetensors
        run: |
          cd output/${{ github.event.inputs.folder_name }}
          for f in *.ts; do mv "$f" "${f%.ts}.safetensors"; done
          mv index.m3u8 index.safetensors
          sed -i 's/\.ts/\.safetensors/g' index.safetensors

      - name: Upload to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          pip install huggingface_hub
          python -c "import os; from huggingface_hub import HfApi; api = HfApi(token=os.environ['HF_TOKEN']); api.upload_folder(folder_path='output/${{ github.event.inputs.folder_name }}', repo_id='Sarko717227/Ai_SMART', repo_type='dataset', path_in_repo='${{ github.event.inputs.folder_name }}')"
